package cn.xmu.edu.legaldocument.algorithm;

import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.parser.PdfTextExtractor;

import java.io.*;
import java.util.ArrayList;

public class WordListConverter {
    //词语列表转化器
    private String filePath;//文件路径
    public static ArrayList<String> uselessWordList;//无用词语列别
    private ArrayList<Integer> recordForSentenceNumber;
    private String allContent;

    public WordListConverter() {

    }

    //初始化
    public WordListConverter(String filePath,String allContent) {
        if (filePath == null){
            this.filePath = "";
        }
        if (allContent == null){
            this.allContent = "";
        }
        this.filePath = filePath;
        this.allContent = allContent;
        constructUselessWordList();
        recordForSentenceNumber = new ArrayList<Integer>();
    }

    public static ArrayList<String> getUselessWordList() {
        return uselessWordList;
    }

    //提取有用信息
    public String extractUsefulInformation() throws IOException {
        String bookContent = ""; // 存放读取出的文档内容
        //判断是传输文件路径还是传输文件内容
        if (this.filePath== null||this.filePath.equals("")){
            bookContent = this.allContent;
        }
        else {
            PdfReader reader = new PdfReader(filePath);
            int num = reader.getNumberOfPages();// 获得页数
            for (int i = 1; i <= num; i++) {
                bookContent += PdfTextExtractor.getTextFromPage(reader, i);
            }
        }
        String usefulContent;//有效信息
        //全变为小写
        bookContent = bookContent.toLowerCase();
        //去掉非英文符号
		bookContent = bookContent.replaceAll("[^a-zA-Z ]", "");
		String firstString = " " + bookContent.substring(0, bookContent.indexOf(" ") + 1);
		boolean flag = true;
        //去掉无用的词语
		for(int startIndex = 0; startIndex < uselessWordList.size(); startIndex++) {
			bookContent = bookContent.replaceAll(uselessWordList.get(startIndex), " ");

			if(flag && firstString.equals(uselessWordList.get(startIndex))) {
				bookContent = bookContent.substring(bookContent.indexOf(" ") + 1);
			}
		}
		//去掉多余的空格
		usefulContent = bookContent.replaceAll("\\s+", " ").trim();

		//检查一遍
        for(int startIndex = 0; startIndex < uselessWordList.size(); startIndex++) {
            String word=uselessWordList.get(startIndex);
            usefulContent = usefulContent.replaceAll(word, " ");
        }
//		System.out.println(usefulContent);
        return usefulContent;
    }

    public ArrayList<Integer> getRecordForSentenceNumber() {
        return this.recordForSentenceNumber;
    }

    private void printArray(ArrayList<Integer> arr) {
        for(int i= 0; i < arr.size(); i++) {
            System.out.println(i + ": " + arr.get(i));
        }
    }

    private void constructUselessWordList() {
        if(uselessWordList == null) {
            uselessWordList = new ArrayList<String>();
            uselessWordList.add(" a ");
            uselessWordList.add(" as ");
            uselessWordList.add(" able ");
            uselessWordList.add(" about ");
            uselessWordList.add(" above ");
            uselessWordList.add(" according ");
            uselessWordList.add(" accordingly ");
            uselessWordList.add(" across ");
            uselessWordList.add(" actually ");
            uselessWordList.add(" after ");
            uselessWordList.add(" afterwards ");
            uselessWordList.add(" again ");
            uselessWordList.add(" against ");
            uselessWordList.add(" aint ");
            uselessWordList.add(" all ");
            uselessWordList.add(" allow ");
            uselessWordList.add(" allows ");
            uselessWordList.add(" almost ");
            uselessWordList.add(" alone ");
            uselessWordList.add(" along ");
            uselessWordList.add(" already ");
            uselessWordList.add(" also ");
            uselessWordList.add(" although ");
            uselessWordList.add(" always ");
            uselessWordList.add(" am ");
            uselessWordList.add(" among ");
            uselessWordList.add(" amongst ");
            uselessWordList.add(" an ");
            uselessWordList.add(" and ");
            uselessWordList.add(" another ");
            uselessWordList.add(" any ");
            uselessWordList.add(" anybody ");
            uselessWordList.add(" anyhow ");
            uselessWordList.add(" anyone ");
            uselessWordList.add(" anything ");
            uselessWordList.add(" anyway ");
            uselessWordList.add(" anyways ");
            uselessWordList.add(" anywhere ");
            uselessWordList.add(" apart ");
            uselessWordList.add(" appear ");
            uselessWordList.add(" appreciate ");
            uselessWordList.add(" appropriate ");
            uselessWordList.add(" are ");
            uselessWordList.add(" arent ");
            uselessWordList.add(" around ");
            uselessWordList.add(" as ");
            uselessWordList.add(" aside ");
            uselessWordList.add(" ask ");
            uselessWordList.add(" asking ");
            uselessWordList.add(" associated ");
            uselessWordList.add(" at ");
            uselessWordList.add(" available ");
            uselessWordList.add(" away ");
            uselessWordList.add(" awfully ");
            uselessWordList.add(" b ");
            uselessWordList.add(" be ");
            uselessWordList.add(" became ");
            uselessWordList.add(" because ");
            uselessWordList.add(" become ");
            uselessWordList.add(" becomes ");
            uselessWordList.add(" becoming ");
            uselessWordList.add(" been ");
            uselessWordList.add(" before ");
            uselessWordList.add(" beforehand ");
            uselessWordList.add(" behind ");
            uselessWordList.add(" being ");
            uselessWordList.add(" believe ");
            uselessWordList.add(" below ");
            uselessWordList.add(" beside ");
            uselessWordList.add(" besides ");
            uselessWordList.add(" best ");
            uselessWordList.add(" better ");
            uselessWordList.add(" between ");
            uselessWordList.add(" beyond ");
            uselessWordList.add(" both ");
            uselessWordList.add(" brief ");
            uselessWordList.add(" but ");
            uselessWordList.add(" by ");
            uselessWordList.add(" c ");
            uselessWordList.add(" c'mon ");
            uselessWordList.add(" c's ");
            uselessWordList.add(" came ");
            uselessWordList.add(" can ");
            uselessWordList.add(" can't ");
            uselessWordList.add(" cannot ");
            uselessWordList.add(" cant ");
            uselessWordList.add(" cause ");
            uselessWordList.add(" causes ");
            uselessWordList.add(" certain ");
            uselessWordList.add(" certainly ");
            uselessWordList.add(" changes ");
            uselessWordList.add(" clearly ");
            uselessWordList.add(" co ");
            uselessWordList.add(" com ");
            uselessWordList.add(" come ");
            uselessWordList.add(" comes ");
            uselessWordList.add(" concerning ");
            uselessWordList.add(" consequently ");
            uselessWordList.add(" consider ");
            uselessWordList.add(" considering ");
            uselessWordList.add(" contain ");
            uselessWordList.add(" containing ");
            uselessWordList.add(" contains ");
            uselessWordList.add(" corresponding ");
            uselessWordList.add(" could ");
            uselessWordList.add(" couldn't ");
            uselessWordList.add(" course ");
            uselessWordList.add(" currently ");
            uselessWordList.add(" d ");
            uselessWordList.add(" definitely ");
            uselessWordList.add(" described ");
            uselessWordList.add(" despite ");
            uselessWordList.add(" did ");
            uselessWordList.add(" didn't ");
            uselessWordList.add(" different ");
            uselessWordList.add(" do ");
            uselessWordList.add(" does ");
            uselessWordList.add(" doesn't ");
            uselessWordList.add(" doing ");
            uselessWordList.add(" don't ");
            uselessWordList.add(" done ");
            uselessWordList.add(" down ");
            uselessWordList.add(" downwards ");
            uselessWordList.add(" during ");
            uselessWordList.add(" e ");
            uselessWordList.add(" each ");
            uselessWordList.add(" edu ");
            uselessWordList.add(" eg ");
            uselessWordList.add(" eight ");
            uselessWordList.add(" either ");
            uselessWordList.add(" else ");
            uselessWordList.add(" elsewhere ");
            uselessWordList.add(" enough ");
            uselessWordList.add(" entirely ");
            uselessWordList.add(" especially ");
            uselessWordList.add(" et ");
            uselessWordList.add(" etc ");
            uselessWordList.add(" even ");
            uselessWordList.add(" ever ");
            uselessWordList.add(" every ");
            uselessWordList.add(" everybody ");
            uselessWordList.add(" everyone ");
            uselessWordList.add(" everything ");
            uselessWordList.add(" everywhere ");
            uselessWordList.add(" ex ");
            uselessWordList.add(" exactly ");
            uselessWordList.add(" example ");
            uselessWordList.add(" except ");
            uselessWordList.add(" f ");
            uselessWordList.add(" far ");
            uselessWordList.add(" few ");
            uselessWordList.add(" fifth ");
            uselessWordList.add(" first ");
            uselessWordList.add(" five ");
            uselessWordList.add(" followed ");
            uselessWordList.add(" following ");
            uselessWordList.add(" follows ");
            uselessWordList.add(" for ");
            uselessWordList.add(" former ");
            uselessWordList.add(" formerly ");
            uselessWordList.add(" forth ");
            uselessWordList.add(" four ");
            uselessWordList.add(" from ");
            uselessWordList.add(" further ");
            uselessWordList.add(" furthermore ");
            uselessWordList.add(" g ");
            uselessWordList.add(" get ");
            uselessWordList.add(" gets ");
            uselessWordList.add(" getting ");
            uselessWordList.add(" given ");
            uselessWordList.add(" gives ");
            uselessWordList.add(" go ");
            uselessWordList.add(" goes ");
            uselessWordList.add(" going ");
            uselessWordList.add(" gone ");
            uselessWordList.add(" got ");
            uselessWordList.add(" gotten ");
            uselessWordList.add(" greetings ");
            uselessWordList.add(" h ");
            uselessWordList.add(" had ");
            uselessWordList.add(" hadn't ");
            uselessWordList.add(" happens ");
            uselessWordList.add(" hardly ");
            uselessWordList.add(" has ");
            uselessWordList.add(" hasn't ");
            uselessWordList.add(" have ");
            uselessWordList.add(" havet ");
            uselessWordList.add(" haven't ");
            uselessWordList.add(" having ");
            uselessWordList.add(" he ");
            uselessWordList.add(" he's ");
            uselessWordList.add(" hello ");
            uselessWordList.add(" help ");
            uselessWordList.add(" hence ");
            uselessWordList.add(" her ");
            uselessWordList.add(" here ");
            uselessWordList.add(" here's ");
            uselessWordList.add(" hereafter ");
            uselessWordList.add(" hereby ");
            uselessWordList.add(" herein ");
            uselessWordList.add(" hereupon ");
            uselessWordList.add(" hers ");
            uselessWordList.add(" herself ");
            uselessWordList.add(" hi ");
            uselessWordList.add(" him ");
            uselessWordList.add(" himself ");
            uselessWordList.add(" his ");
            uselessWordList.add(" hither ");
            uselessWordList.add(" hopefully ");
            uselessWordList.add(" how ");
            uselessWordList.add(" howbeit ");
            uselessWordList.add(" however ");
            uselessWordList.add(" i ");
            uselessWordList.add(" i'd ");
            uselessWordList.add(" i'll ");
            uselessWordList.add(" i'm ");
            uselessWordList.add(" i've ");
            uselessWordList.add(" ie ");
            uselessWordList.add(" if ");
            uselessWordList.add(" ignored ");
            uselessWordList.add(" immediate ");
            uselessWordList.add(" in ");
            uselessWordList.add(" inasmuch ");
            uselessWordList.add(" inc ");
            uselessWordList.add(" indeed ");
            uselessWordList.add(" indicate ");
            uselessWordList.add(" indicated ");
            uselessWordList.add(" indicates ");
            uselessWordList.add(" inner ");
            uselessWordList.add(" insofar ");
            uselessWordList.add(" instead ");
            uselessWordList.add(" into ");
            uselessWordList.add(" inward ");
            uselessWordList.add(" is ");
            uselessWordList.add(" isn't ");
            uselessWordList.add(" it ");
            uselessWordList.add(" it'd ");
            uselessWordList.add(" it'll ");
            uselessWordList.add(" it's ");
            uselessWordList.add(" its ");
            uselessWordList.add(" itself ");
            uselessWordList.add(" j ");
            uselessWordList.add(" just ");
            uselessWordList.add(" k ");
            uselessWordList.add(" keep ");
            uselessWordList.add(" keeps ");
            uselessWordList.add(" kept ");
            uselessWordList.add(" know ");
            uselessWordList.add(" knows ");
            uselessWordList.add(" known ");
            uselessWordList.add(" l ");
            uselessWordList.add(" last ");
            uselessWordList.add(" lately ");
            uselessWordList.add(" later ");
            uselessWordList.add(" latter ");
            uselessWordList.add(" latterly ");
            uselessWordList.add(" least ");
            uselessWordList.add(" less ");
            uselessWordList.add(" lest ");
            uselessWordList.add(" let ");
            uselessWordList.add(" let's ");
            uselessWordList.add(" like ");
            uselessWordList.add(" liked ");
            uselessWordList.add(" likely ");
            uselessWordList.add(" little ");
            uselessWordList.add(" look ");
            uselessWordList.add(" looking ");
            uselessWordList.add(" looks ");
            uselessWordList.add(" ltd ");
            uselessWordList.add(" m ");
            uselessWordList.add(" mainly ");
            uselessWordList.add(" many ");
            uselessWordList.add(" may ");
            uselessWordList.add(" maybe ");
            uselessWordList.add(" me ");
            uselessWordList.add(" mean ");
            uselessWordList.add(" meanwhile ");
            uselessWordList.add(" merely ");
            uselessWordList.add(" might ");
            uselessWordList.add(" more ");
            uselessWordList.add(" moreover ");
            uselessWordList.add(" most ");
            uselessWordList.add(" mostly ");
            uselessWordList.add(" much ");
            uselessWordList.add(" must ");
            uselessWordList.add(" my ");
            uselessWordList.add(" myself ");
            uselessWordList.add(" n ");
            uselessWordList.add(" name ");
            uselessWordList.add(" namely ");
            uselessWordList.add(" nd ");
            uselessWordList.add(" near ");
            uselessWordList.add(" nearly ");
            uselessWordList.add(" necessary ");
            uselessWordList.add(" need ");
            uselessWordList.add(" needs ");
            uselessWordList.add(" neither ");
            uselessWordList.add(" never ");
            uselessWordList.add(" nevertheless ");
            uselessWordList.add(" new ");
            uselessWordList.add(" next ");
            uselessWordList.add(" nine ");
            uselessWordList.add(" no ");
            uselessWordList.add(" nobody ");
            uselessWordList.add(" non ");
            uselessWordList.add(" none ");
            uselessWordList.add(" noone ");
            uselessWordList.add(" nor ");
            uselessWordList.add(" normally ");
            uselessWordList.add(" not ");
            uselessWordList.add(" nothing ");
            uselessWordList.add(" novel ");
            uselessWordList.add(" now ");
            uselessWordList.add(" nowhere ");
            uselessWordList.add(" o ");
            uselessWordList.add(" obviously ");
            uselessWordList.add(" of ");
            uselessWordList.add(" off ");
            uselessWordList.add(" often ");
            uselessWordList.add(" oh ");
            uselessWordList.add(" ok ");
            uselessWordList.add(" okay ");
            uselessWordList.add(" old ");
            uselessWordList.add(" on ");
            uselessWordList.add(" once ");
            uselessWordList.add(" one ");
            uselessWordList.add(" ones ");
            uselessWordList.add(" only ");
            uselessWordList.add(" onto ");
            uselessWordList.add(" or ");
            uselessWordList.add(" other ");
            uselessWordList.add(" others ");
            uselessWordList.add(" otherwise ");
            uselessWordList.add(" ought ");
            uselessWordList.add(" our ");
            uselessWordList.add(" ours ");
            uselessWordList.add(" ourselves ");
            uselessWordList.add(" out ");
            uselessWordList.add(" outside ");
            uselessWordList.add(" over ");
            uselessWordList.add(" overall ");
            uselessWordList.add(" own ");
            uselessWordList.add(" p ");
            uselessWordList.add(" particular ");
            uselessWordList.add(" particularly ");
            uselessWordList.add(" per ");
            uselessWordList.add(" perhaps ");
            uselessWordList.add(" placed ");
            uselessWordList.add(" please ");
            uselessWordList.add(" plus ");
            uselessWordList.add(" possible ");
            uselessWordList.add(" presumably ");
            uselessWordList.add(" probably ");
            uselessWordList.add(" provides ");
            uselessWordList.add(" q ");
            uselessWordList.add(" que ");
            uselessWordList.add(" quite ");
            uselessWordList.add(" qv ");
            uselessWordList.add(" r ");
            uselessWordList.add(" rather ");
            uselessWordList.add(" rd ");
            uselessWordList.add(" re ");
            uselessWordList.add(" really ");
            uselessWordList.add(" reasonably ");
            uselessWordList.add(" regarding ");
            uselessWordList.add(" regardless ");
            uselessWordList.add(" regards ");
            uselessWordList.add(" relatively ");
            uselessWordList.add(" respectively ");
            uselessWordList.add(" right ");
            uselessWordList.add(" s ");
            uselessWordList.add(" said ");
            uselessWordList.add(" same ");
            uselessWordList.add(" saw ");
            uselessWordList.add(" say ");
            uselessWordList.add(" saying ");
            uselessWordList.add(" says ");
            uselessWordList.add(" second ");
            uselessWordList.add(" secondly ");
            uselessWordList.add(" see ");
            uselessWordList.add(" seeing ");
            uselessWordList.add(" seem ");
            uselessWordList.add(" seemed ");
            uselessWordList.add(" seeming ");
            uselessWordList.add(" seems ");
            uselessWordList.add(" seen ");
            uselessWordList.add(" self ");
            uselessWordList.add(" selves ");
            uselessWordList.add(" sensible ");
            uselessWordList.add(" sent ");
            uselessWordList.add(" serious ");
            uselessWordList.add(" seriously ");
            uselessWordList.add(" seven ");
            uselessWordList.add(" several ");
            uselessWordList.add(" shall ");
            uselessWordList.add(" she ");
            uselessWordList.add(" should ");
            uselessWordList.add(" shouldn't ");
            uselessWordList.add(" since ");
            uselessWordList.add(" six ");
            uselessWordList.add(" so ");
            uselessWordList.add(" some ");
            uselessWordList.add(" somebody ");
            uselessWordList.add(" somehow ");
            uselessWordList.add(" someone ");
            uselessWordList.add(" something ");
            uselessWordList.add(" sometime ");
            uselessWordList.add(" sometimes ");
            uselessWordList.add(" somewhat ");
            uselessWordList.add(" somewhere ");
            uselessWordList.add(" soon ");
            uselessWordList.add(" sorry ");
            uselessWordList.add(" specified ");
            uselessWordList.add(" specify ");
            uselessWordList.add(" specifying ");
            uselessWordList.add(" still ");
            uselessWordList.add(" sub ");
            uselessWordList.add(" such ");
            uselessWordList.add(" sup ");
            uselessWordList.add(" sure ");
            uselessWordList.add(" t ");
            uselessWordList.add(" t's ");
            uselessWordList.add(" take ");
            uselessWordList.add(" taken ");
            uselessWordList.add(" tell ");
            uselessWordList.add(" tends ");
            uselessWordList.add(" th ");
            uselessWordList.add(" than ");
            uselessWordList.add(" thank ");
            uselessWordList.add(" thanks ");
            uselessWordList.add(" thanx ");
            uselessWordList.add(" that ");
            uselessWordList.add(" that's ");
            uselessWordList.add(" thats ");
            uselessWordList.add(" the ");
            uselessWordList.add(" their ");
            uselessWordList.add(" theirs ");
            uselessWordList.add(" them ");
            uselessWordList.add(" themselves ");
            uselessWordList.add(" then ");
            uselessWordList.add(" thence ");
            uselessWordList.add(" there ");
            uselessWordList.add(" there's ");
            uselessWordList.add(" thereafter ");
            uselessWordList.add(" thereby ");
            uselessWordList.add(" therefore ");
            uselessWordList.add(" therein ");
            uselessWordList.add(" theres ");
            uselessWordList.add(" thereupon ");
            uselessWordList.add(" these ");
            uselessWordList.add(" they ");
            uselessWordList.add(" they'd ");
            uselessWordList.add(" they'll ");
            uselessWordList.add(" they're ");
            uselessWordList.add(" they've ");
            uselessWordList.add(" think ");
            uselessWordList.add(" third ");
            uselessWordList.add(" this ");
            uselessWordList.add(" thorough ");
            uselessWordList.add(" thoroughly ");
            uselessWordList.add(" those ");
            uselessWordList.add(" though ");
            uselessWordList.add(" three ");
            uselessWordList.add(" through ");
            uselessWordList.add(" throughout ");
            uselessWordList.add(" thru ");
            uselessWordList.add(" thus ");
            uselessWordList.add(" to ");
            uselessWordList.add(" together ");
            uselessWordList.add(" too ");
            uselessWordList.add(" took ");
            uselessWordList.add(" toward ");
            uselessWordList.add(" towards ");
            uselessWordList.add(" tried ");
            uselessWordList.add(" tries ");
            uselessWordList.add(" truly ");
            uselessWordList.add(" try ");
            uselessWordList.add(" trying ");
            uselessWordList.add(" twice ");
            uselessWordList.add(" two ");
            uselessWordList.add(" u ");
            uselessWordList.add(" un ");
            uselessWordList.add(" under ");
            uselessWordList.add(" unfortunately ");
            uselessWordList.add(" unless ");
            uselessWordList.add(" unlikely ");
            uselessWordList.add(" until ");
            uselessWordList.add(" unto ");
            uselessWordList.add(" up ");
            uselessWordList.add(" upon ");
            uselessWordList.add(" us ");
            uselessWordList.add(" use ");
            uselessWordList.add(" used ");
            uselessWordList.add(" useful ");
            uselessWordList.add(" uses ");
            uselessWordList.add(" using ");
            uselessWordList.add(" usually ");
            uselessWordList.add(" uucp ");
            uselessWordList.add(" v ");
            uselessWordList.add(" value ");
            uselessWordList.add(" various ");
            uselessWordList.add(" very ");
            uselessWordList.add(" via ");
            uselessWordList.add(" viz ");
            uselessWordList.add(" vs ");
            uselessWordList.add(" w ");
            uselessWordList.add(" want ");
            uselessWordList.add(" wants ");
            uselessWordList.add(" was ");
            uselessWordList.add(" wasn't ");
            uselessWordList.add(" way ");
            uselessWordList.add(" we ");
            uselessWordList.add(" we'd ");
            uselessWordList.add(" we'll ");
            uselessWordList.add(" we're ");
            uselessWordList.add(" we've ");
            uselessWordList.add(" welcome ");
            uselessWordList.add(" well ");
            uselessWordList.add(" went ");
            uselessWordList.add(" were ");
            uselessWordList.add(" weren't ");
            uselessWordList.add(" what ");
            uselessWordList.add(" what's ");
            uselessWordList.add(" whatever ");
            uselessWordList.add(" when ");
            uselessWordList.add(" whence ");
            uselessWordList.add(" whenever ");
            uselessWordList.add(" where ");
            uselessWordList.add(" where's ");
            uselessWordList.add(" whereafter ");
            uselessWordList.add(" whereas ");
            uselessWordList.add(" whereby ");
            uselessWordList.add(" wherein ");
            uselessWordList.add(" whereupon ");
            uselessWordList.add(" wherever ");
            uselessWordList.add(" whether ");
            uselessWordList.add(" which ");
            uselessWordList.add(" while ");
            uselessWordList.add(" whither ");
            uselessWordList.add(" who ");
            uselessWordList.add(" who's ");
            uselessWordList.add(" whoever ");
            uselessWordList.add(" whole ");
            uselessWordList.add(" whom ");
            uselessWordList.add(" whose ");
            uselessWordList.add(" why ");
            uselessWordList.add(" will ");
            uselessWordList.add(" willing ");
            uselessWordList.add(" wish ");
            uselessWordList.add(" with ");
            uselessWordList.add(" within ");
            uselessWordList.add(" without ");
            uselessWordList.add(" won't ");
            uselessWordList.add(" wonder ");
            uselessWordList.add(" would ");
            uselessWordList.add(" wouldn't ");
            uselessWordList.add(" x ");
            uselessWordList.add(" y ");
            uselessWordList.add(" yes ");
            uselessWordList.add(" yet ");
            uselessWordList.add(" you ");
            uselessWordList.add(" you'd ");
            uselessWordList.add(" you'll ");
            uselessWordList.add(" you're ");
            uselessWordList.add(" you've ");
            uselessWordList.add(" your ");
            uselessWordList.add(" yours ");
            uselessWordList.add(" yourself ");
            uselessWordList.add(" yourselves ");
            uselessWordList.add(" z ");
            uselessWordList.add(" zero ");
            uselessWordList.add(" dont ");
        }
    }
}
